import 'package:agenda/utils/models.dart';

List<ModelEstado> estados = const [
  ModelEstado(id: 12, nome: 'Acre', sigla: 'AC'),
  ModelEstado(id: 27, nome: 'Alagoas', sigla: 'AL'),
  ModelEstado(id: 16, nome: 'Amapá', sigla: 'AP'),
  ModelEstado(id: 13, nome: 'Amazonas', sigla: 'AM'),
  ModelEstado(id: 29, nome: 'Bahia', sigla: 'BA'),
  ModelEstado(id: 23, nome: 'Ceará', sigla: 'CE'),
  ModelEstado(id: 53, nome: 'Distrito Federal', sigla: 'DF'),
  ModelEstado(id: 32, nome: 'Espírito Santo', sigla: 'ES'),
  ModelEstado(id: 52, nome: 'Goiás', sigla: 'GO'),
  ModelEstado(id: 21, nome: 'Maranhão', sigla: 'MA'),
  ModelEstado(id: 51, nome: 'Mato Grosso', sigla: 'MT'),
  ModelEstado(id: 50, nome: 'Mato Grosso do Sul', sigla: 'MS'),
  ModelEstado(id: 31, nome: 'Minas Gerais', sigla: 'MG'),
  ModelEstado(id: 15, nome: 'Pará', sigla: 'PA'),
  ModelEstado(id: 25, nome: 'Paraíba', sigla: 'PB'),
  ModelEstado(id: 41, nome: 'Paraná', sigla: 'PR'),
  ModelEstado(id: 26, nome: 'Pernambuco', sigla: 'PE'),
  ModelEstado(id: 22, nome: 'Piauí', sigla: 'PI'),
  ModelEstado(id: 33, nome: 'Rio de Janeiro', sigla: 'RJ'),
  ModelEstado(id: 24, nome: 'Rio Grande do Norte', sigla: 'RN'),
  ModelEstado(id: 43, nome: 'Rio Grande do Sul', sigla: 'RS'),
  ModelEstado(id: 11, nome: 'Rondônia', sigla: 'RO'),
  ModelEstado(id: 14, nome: 'Roraima', sigla: 'RR'),
  ModelEstado(id: 42, nome: 'Santa Catarina', sigla: 'SC'),
  ModelEstado(id: 35, nome: 'São Paulo', sigla: 'SP'),
  ModelEstado(id: 28, nome: 'Sergipe', sigla: 'SE'),
  ModelEstado(id: 17, nome: 'Tocantins', sigla: 'TO'),
];
